export const RECORD_USERINFO = 'RECORD_USERINFO'
export const GET_USERINFO = 'GET_USERINFO'
export const OUT_LOGIN = 'OUT_LOGIN'
export const PAYMENT_INFO = 'PAYMENT_INFO'
export const BANK_INFO = 'BANK_INFO'